### ISSUE TITLE
removeLargeErrs keyword not working in plot_overlay

### ISSUE THREAD

**Issue by kherli** [cmeeren/eiscatscanplot#1]
Hi!

Thanks for the fan plotting software, it's been very useful! I have been trying to do some filtering of the plotted data but if I run your advanced.py script I'm getting the error:
ufunc 'add' did not contain a loop with signature matching types dtype('S32') dtype('S32') dtype('S32')

when I set the removeLargeErrs keyword. Any ideas why?

**Comment by cmeeren** [comment]
Absolutely no idea, sorry. I've long since moved on from academia and stopped using and supporting this. Could be an incompatibility with a newer version of numpy for all I know. Hope you get it working!

**Comment by kherli** [comment]
Ah okay, no worries - thanks for letting me know! :)
